# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_wts_ATE <- function(p, TI) {
    .Call(`_entbal_make_wts_ATE`, p, TI)
}

make_wts_ATT <- function(p, TI) {
    .Call(`_entbal_make_wts_ATT`, p, TI)
}

make_wts_ATC <- function(p, TI) {
    .Call(`_entbal_make_wts_ATC`, p, TI)
}

make_wts_ATO <- function(p, TI) {
    .Call(`_entbal_make_wts_ATO`, p, TI)
}

#' Calculate a weighted mean conditioned upon a vector of group indicators
#'
#' @param X Vector of observed covariate values
#' @param TI Vector representing group membership, i.e., \code{TI = (0, 1, 0, ...)}, where 1 indicates group membership
#' @param w Vector of weights, these need not sum to one in each group and are normalized in the equation
#' @return Estimate of the weighted mean in the group represented by \code{TI}
#' @export
wtd_mean <- function(X, TI, w) {
    .Call(`_entbal_wtd_mean`, X, TI, w)
}

#' Calculate an estimate of the weighted raw moment \eqn{E(X^{p})} conditioned upon a vector of group indicators
#'
#' @param X Vector of observed covariate values
#' @param TI Vector representing group membership, i.e., \code{TI = (0, 1, 0, ...)}, where 1 indicates group membership
#' @param w Vector of weights, these need not sum to one in each group and are normalized in the equation
#' @param mom Power \eqn{p} of the required moment estimate
#' @return Estimate of the weighted raw moment in the group represented by \code{TI}
#' @export
wtd_moment <- function(X, TI, w, mom = 1L) {
    .Call(`_entbal_wtd_moment`, X, TI, w, mom)
}

#' Calculate a weighted variance conditioned upon a vector of group indicators
#'
#' @param X Vector of observed covariate values
#' @param TI Vector representing group membership, i.e., \code{TI = (0, 1, 0, ...)}, where 1 indicates group membership
#' @param w Vector of weights, these need not sum to one in each group and are normalized in the equation
#' @return Estimate of the weighted variance in the group represented by \code{TI}
#' @export
wtd_sd2 <- function(X, TI, w) {
    .Call(`_entbal_wtd_sd2`, X, TI, w)
}

.cov_mean_bal <- function(X, TI, w) {
    .Call(`_entbal_cov_mean_bal`, X, TI, w)
}

.cov_var_bal <- function(X, TI, w) {
    .Call(`_entbal_cov_var_bal`, X, TI, w)
}

est_binary_te <- function(YO, TI, wts) {
    .Call(`_entbal_est_binary_te`, YO, TI, wts)
}

std_diff_means <- function(X, TA, wts) {
    .Call(`_entbal_std_diff_means`, X, TA, wts)
}

log_sd_ratio <- function(X, TA, wts) {
    .Call(`_entbal_log_sd_ratio`, X, TA, wts)
}

group_ESS <- function(w, TI) {
    .Call(`_entbal_group_ESS`, w, TI)
}

ESS <- function(w) {
    .Call(`_entbal_ESS`, w)
}

